#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'google/protobuf/timestamp.pb'; rescue LoadError; end

module Metric
  # forward declarations
  class ProcessInfo < ::ProtocolBuffers::Message; end
  class Metric < ::ProtocolBuffers::Message; end

  class ProcessInfo < ::ProtocolBuffers::Message
    set_fully_qualified_name "metric.ProcessInfo"

    optional :int32, :pid, 1
    optional :string, :name, 2
    optional :double, :cpu_percent, 3
    optional :double, :memory_usage, 4
  end

  class Metric < ::ProtocolBuffers::Message
    set_fully_qualified_name "metric.Metric"

    optional :string, :host_id, 1
    optional :string, :hostname, 2
    optional ::Google::Protobuf::Timestamp, :sent_at, 3
    repeated ::Metric::ProcessInfo, :processes, 4
  end

end
