# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/wathermg/topmetrics/pkg/metric/models.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("github.com/wathermg/topmetrics/pkg/metric/models.proto", :syntax => :proto3) do
    add_message "metric.ProcessInfo" do
      optional :pid, :int32, 1
      optional :name, :string, 2
      optional :cpu_percent, :double, 3
      optional :memory_usage, :double, 4
    end
    add_message "metric.Metric" do
      optional :host_id, :string, 1
      optional :hostname, :string, 2
      optional :sent_at, :message, 3, "google.protobuf.Timestamp"
      repeated :processes, :message, 4, "metric.ProcessInfo"
    end
  end
end

module Metric
  ProcessInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("metric.ProcessInfo").msgclass
  Metric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("metric.Metric").msgclass
end
