# Уровень логирования
log.level: info

# Задержка между проверками конфигурации (в секундах)
config.reload.interval: 3s

# Включить автоматическую перезагрузку конфигурации
config.reload.automatic: true