- pipeline.id: topmetric_beats
#  pipeline.workers: 4
  pipeline.batch.size: 125
  path.config: "./config/pipelines/topmetrics_logs.conf"
#- pipeline.id: topmetrics_json
#  path.config: "/.config/pipelines/topmetrics_json.conf"